repos:
  distonic:
    url: .
    branches:
    - master
    - develop
    - feature/*
    interval: 1m
data_dir: /tmp/distonic_home
worker:
  concurrency: 3
artefactory:
  storage:
    backend: mongodb
    mongodb:
      url: mongodb
...